### ISSUE TITLE
Copyright year outdated

### ISSUE THREAD

**Issue by rugk** [haskell-infra/www.haskell.org#27]
It's 2020 *ding* *dong*

Still shows 2019 in the footer.

**Comment by TikhonJelvis** [comment]
Thanks for catching this. It should be fixed next time we deploy the site. (Deploying is currently held up a bit by some internal technical difficulties...)

**Comment by gwils** [comment]
I have redeployed the site. The homepage still shows 2019, but other pages (downloads, community, etc.) correctly show 2020. I haven't had time to look into why yet.

**Comment by TikhonJelvis** [comment]
Copyright date on the home page has been updated too now.

![haskell-org-copyright-2020](https://user-images.githubusercontent.com/624310/93154372-56450280-f6b8-11ea-8443-1bfe073077c0.png)

Looks like it only gets updated when the page *changes*. Given the way copyright dates work, this seems okay to me.
